
SELECT Z.FASTIGHETSBETECKNING KIR, X.FNR, Z.DIARIENUMMER AS DIARIENR
FROM [tempExcel].DBO.[påminnelse-12-mån-2020_1] Z
    LEFT OUTER JOIN GISDATA.[sde_geofir_gotland].[gng].FA_FASTIGHET X ON Z.FASTIGHETSBETECKNING = X.BETECKNING
