USE [tempExcel]
GO
BEGIN
    DECLARE @ARENDENR TT_ENDASTUNIKAARENDEN
    INSERT
    INTO @ARENDENR
    SELECT *
    FROM tempExcel.dbo.[SlutgiltigLista Förbud1 2020]
    DECLARE @ARENDENFAS HANDELSETABLETYPE
    INSERT
    INTO @ARENDENFAS (DIARIENUMMER, FASTIGHET, RUBRIK, DATUM)
    SELECT *, '', 2020 - 10 - 10
    FROM TEMPEXCEL.DBO.[p�minnelse-12-m�n-2020_1]

    DECLARE @RESULT INT

    EXEC
	@RESULT = Cp_Forbud1Utsok
		  @ARENDENR,
		  @ARENDENFAS
    SELECT @RESULT AS RESULT

END