
SELECT TEMPEXCEL.DBO.up_xSplitStringByDelim(X.FLIKEN_ÄRENDEN, 2, '-')                                             YEAR
     , right(right(X.FLIKEN_ÄRENDEN, (len(X.FLIKEN_ÄRENDEN) - charindex('-', X.FLIKEN_ÄRENDEN))),
	     len(right(X.FLIKEN_ÄRENDEN, (len(X.FLIKEN_ÄRENDEN) - charindex('-', X.FLIKEN_ÄRENDEN)))) -
	     charindex('-', right(X.FLIKEN_ÄRENDEN, (len(X.FLIKEN_ÄRENDEN) - charindex('-', X.FLIKEN_ÄRENDEN))))) NR
FROM (SELECT FLIKEN_ÄRENDEN FROM TEMPEXCEL.DBO.SOL19_4KOL GROUP BY FLIKEN_ÄRENDEN) X
    LEFT OUTER JOIN TEMPEXCEL.DBO.SOL19_ÄRENDENRATTJOINA ON FLIKEN_ÄRENDEN = SOL19_ÄRENDENRATTJOINA.DIARIENUMMER
WHERE DIARIENUMMER IS NULL AND FLIKEN_ÄRENDEN <> '0' AND FLIKEN_ÄRENDEN <> 'anteckning'
