--input table that might be sentr from other method
USE GISDATA.SDE_GEOFIR_GOTLAND;

ALTER TABLE HÄNDELSERFÖRBUD12020
    ADD CONSTRAINT HÄNDELSERFÖRBUD12020_PK
	PRIMARY KEY NONCLUSTERED (DIARIENUMMER)
GO
;

UPDATE SOL19_4KOL
SET ROWNR = (SELECT row_number() OVER (PARTITION BY OBJEKTID ORDER BY FNR))
WHERE 1 = 1;

SELECT * FROM BOK12 WHERE FLIKEN_ÄRENDEN IS NOT NULL;
SELECT * FROM DBO.kirToFnr(.) X;
SELECT * FROM DBO.kirToFnr(SELECT * FROM [påminnelse-12-mån-2020_1]) X;
SELECT *
FROM SOL19_4KOL
    RIGHT OUTER JOIN SOL19_ÄRENDENRATTJOINA S19ÄAJ ON SOL19_4KOL.FNR = S19ÄAJ.FNR
ORDER BY [order];
SELECT SOL19_4KOL.FNR, PUNKTTYPAB, FLIKEN_KOORDINATER, DIARIENUMMER, OBJEKTID
FROM SOL19_4KOL
    LEFT OUTER JOIN SOL19_ÄRENDENRATTJOINA S19ÄAJ ON SOL19_4KOL.FNR = S19ÄAJ.FNR

