;
IF object_id('tempdb..fordig') IS NULL BEGIN
    BEGIN TRANSACTION ;
    COMMIT TRANSACTION;
END;
WITH
    FOANAD AS (SELECT DISTINCT concat('MBNV-2020-', FD.DIARIENUMMER) DIARIENUMMER
			     , FD.FASTIGHET                          FNR
			     , FOANA.NAMN
			     , ADRESS
			     , FOANA.POSTORT
			     , POSTNR
	       FROM  tempdb.dbo.##PATO FOANA
		   RIGHT OUTER JOIN @INPUTFNR FD ON FD.FNR = FOANA.FNR)

SELECT DIARIENUMMER
     , concat(FOANAD.NAMN, ' ', FOANAD.ADRESS, ' ', FOANAD.POSTORT, ' ', FOANAD.POSTNR) AS C
     , Q.READRESS
     , Q.ÄGARE
     , Q.ADRESS
FROM FOANAD
    LEFT OUTER JOIN
FASADRESSER Q ON FNR = Q.NAMN AND Q.ÄGARE = FOANAD.NAMN
