select * from INFORMATION_SCHEMA.VIEW_TABLE_USAGE WHERE VIEW_NAME = 'vwAehAerende'

SELECT COLUMN_NAME,TABLE_NAME from INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME like 'tbAehAerende%' ORDER BY COLUMN_NAME