:r FnrToAdress/Samboende.sql

SELECT *
FROM (SELECT FASTIGHET
      FROM [20201108ChristofferR?knarExcel]
      GROUP BY FASTIGHET
      UNION
      SELECT FASTIGHETSBETECKNING
      FROM [20201112Flaggor ?garuppgifter-nyutskick]
      GROUP BY FASTIGHETSBETECKNING) AS [20201108CREF20201112F ?-nF]
WHERE NOT (FASTIGHET IN (SELECT FNR FROM SAMMBOENDE))
SELECT KIR
FROM (SELECT Z.DIA, Z.KIR, X.FNR
      FROM (SELECT INTDIARIENUMMERLOEPNUMMER DIA, STRFASTIGHETSBETECKNING KIR, STRFNRID FNR
	    FROM [admsql04].[EDPVisionRegionGotland].DBO.VWAEHAERENDE
	    WHERE STRAERENDEMENING = 'Klart vatten - information om avlopp' AND INTDIARIEAAR = 2020) AS Z
	  LEFT OUTER JOIN [gisdata].[sde_geofir_gotland].[gng].FA_FASTIGHET X ON Z.KIR = X.BETECKNING
      WHERE NOT (DIA IN (SELECT DIARIENUMMER FROM SAMMBOENDE GROUP BY DIARIENUMMER))) Q
    LEFT OUTER JOIN TEMPEXCEL.DBO.[20201112Flaggor ?garuppgifter-nyutskick] Y ON Y.FASTIGHETSNYCKEL = Q.FNR