/*
andel as float
then check that the sum of andelar does fit the bill
*/

DECLARE @LOCAL_TABLEVARIABLE TABLE
(FNR         INTEGER,
 UA_UTADR2   NVARCHAR(MAX),
 ANDELX      NVARCHAR(20),
 INSKDATUM   DATETIME,
 UA_UTADR1   NVARCHAR(MAX),
 UA_LAND     NVARCHAR(MAX),
 SAL_POSTORT NVARCHAR(MAX),
 SAL_POSTNR  NVARCHAR(MAX),
 NAMN        NVARCHAR(MAX),
 KORTNAMN    NVARCHAR(MAX),
 FAL_UTADR2  NVARCHAR(MAX),
 FAL_POSTORT NVARCHAR(MAX),
 FAL_POSTNR  NVARCHAR(MAX),
 SAL_UTADR1  NVARCHAR(MAX),
 PERSORGNR   NVARCHAR(MAX),
 ANDEL       AS cast(left(ANDELX, charindex('/', ANDELX, 1) - 1) AS FLOAT) /
		cast(right(ANDELX, len(ANDELX) - charindex('/', ANDELX, 1)) AS FLOAT))

INSERT
INTO @LOCAL_TABLEVARIABLE (FNR, ANDELX, INSKDATUM, [UA_UTADR1], [UA_LAND], [SAL_POSTORT], [SAL_POSTNR], [NAMN], [KORTNAMN], [FAL_UTADR2], [FAL_POSTORT], [FAL_POSTNR], [SAL_UTADR1], [PERSORGNR])
SELECT FNR
     , ANDEL
     , INSKDATUM
     , [UA_UTADR1]
     , [UA_LAND]
     , [SAL_POSTORT]
     , [SAL_POSTNR]
     , [NAMN]
     , [KORTNAMN]
     , [FAL_UTADR2]
     , [FAL_POSTORT]
     , [FAL_POSTNR]
     , [SAL_UTADR1]
     , [PERSORGNR]

FROM SDE_GEOFIR_GOTLAND.GNG.FA_LAGFART_V2
WHERE FNR IN (90035318, 90000487, 90028363, 90000807, 90042089, 90000849, 90061888, 90035635, 90028359);
WITH
    ASD AS (SELECT *, row_number() OVER (PARTITION BY FNR ORDER BY INSKDATUM,ANDEL) ÄGARORDNING
	    FROM @LOCAL_TABLEVARIABLE)

SELECT FNR, ANDEL, NAMN, SUM(ANDEL) OVER (PARTITION BY FNR ORDER BY ÄGARORDNING) AS AGENDEPROCENTIORDNING
FROM ASD
