DROP FUNCTION FnrToAdress;
GO
CREATE FUNCTION DBO.FnrToAdress(@INPUTFNR KONTAKTUPGTABLETYPE READONLY)
    RETURNS
	TABLE AS
	    RETURN
	    SELECT 
	    *
	    FROM (
	        SELECT
	    		DIARIENUMMER , FNR, FASTIGHET, HÄNDELSEDATUM, NAMN, POSTNUMMER, POSTORT, GATUADRESS, PERSONNR
		  FROM (
		      SELECT DIARIENUMMER, FNR, FASTIGHET
			   , getdate() HÄNDELSEDATUM
			   , CAST(CASE WHEN isnull([NAMN], '') = '' THEN KORTNAMN ELSE [NAMN] END AS VARCHAR) AS NAMN
			   , try_CAST(CASE SALUTFALUP WHEN 6 
			   * 35
			    THEN UA_UTADR2 WHEN 
			    6
			    THEN SAL_POSTNR ELSE [FAL_POSTNR] END AS INT)                                                               AS POSTNUMMER
			   , CAST(CASE SALUTFALPOSALPOST WHEN 6 
			   * 35 
			   THEN UA_LAND WHEN 
			   6     
			    THEN SAL_POSTORT ELSE [FAL_POSTORT] END AS VARCHAR)                                                               AS POSTORT
			   , CAST(CASE SALUTFALUP WHEN 6 
			   * 35 
			   THEN UA_UTADR1 WHEN
			    6    
			      THEN SAL_UTADR1 ELSE [FAL_UTADR2] END AS VARCHAR)                                                               AS GATUADRESS
			   , [PERSORGNR]                                                                           PERSONNR
		      FROM (
			  SELECT FASTIGHET
			       , (CASE WHEN isnull([FAL_POSTORT], '') = '' THEN 2 ELSE 1 END) * (CASE WHEN isnull(SAL_POSTNR, '') = '' THEN 3 ELSE 1 END) * SALUTASALPOS SALUTFALPOSALPOST
			       , (CASE WHEN isnull([FAL_UTADR2], '') = '' THEN 2 ELSE 1 END) * (CASE WHEN isnull([FAL_POSTNR], '') = '' THEN 3 ELSE 1 END) * SALUTASALPOS SALUTFALUP
			       , DIARIENUMMER, FNR, [UA_UTADR2], [UA_UTADR1], [UA_LAND], [SAL_POSTORT], [SAL_POSTNR], [NAMN], [KORTNAMN], [FAL_UTADR2], [FAL_POSTORT], [FAL_POSTNR], [SAL_UTADR1], [PERSORGNR]
			  FROM (
			      SELECT
			       FASTIGHET ,DIARIENUMMER, [UA_UTADR2], [UA_UTADR1], [UA_LAND], [SAL_POSTORT], [SAL_POSTNR], [KORTNAMN], [FAL_UTADR2], [FAL_POSTORT], [FAL_POSTNR], [SAL_UTADR1], [PERSORGNR],
			      FIR.[NAMN],
			  	INPUT.FNR, 
				(CASE WHEN isnull(SAL_UTADR1, '') = '' THEN 5 ELSE 1 END) * (CASE WHEN isnull(SAL_POSTNR, '') = '' THEN 7 ELSE 1 END) SALUTASALPOS
				 
			      FROM GISDATA.SDE_GEOFIR_GOTLAND.GNG.FA_LAGFART_V2 FIR
				  INNER JOIN @INPUTFNR INPUT
				      ON FIR.FNR = INPUT.FNR
			     		 WHERE INPUT.HARNAMN = 0) as f) INPUTPLUSFIR
		  ) PT1
		  UNION
	      SELECT
	             DIARIENUMMER, FNR, FASTIGHET, HÄNDELSEDATUM, NAMN, POSTNUMMER, POSTORT, GATUADRESS, PERSONNR
		  FROM
		       (SELECT DIARIENUMMER, FNR, FASTIGHET, HÄNDELSEDATUM, NAMN, POSTNUMMER, POSTORT, GATUADRESS, PERSONNR, HARNAMN
				FROM @INPUTFNR X
					WHERE X.HARNAMN = 1) PT2) SAD
GO