
SELECT MAX(NRX) I, MAX(ANDEL) ANDEL, POSTORT, POSTNUMMER, ADRESS, NAMN, BETECKNING, ARENDENR
FROM (SELECT row_number() OVER (ORDER BY newid()) NRX
	   , cast(BETECKNING AS VARCHAR(100))     BETECKNING
	   , cast(ÄRNDENR AS VARCHAR(100))        ARENDENR
	   , cast(ANDEL AS VARCHAR(100))          ANDEL
	   , cast(NAMN AS VARCHAR(100))           NAMN
	   , cast(ADRESS AS VARCHAR(100))         ADRESS
	   , cast(POSTNUMMER AS VARCHAR(100))     POSTNUMMER
	   , cast(POSTORT AS VARCHAR(100))        POSTORT
      FROM TEMPEXCEL.DBO.GENERATOR_INPUTPLUSGEOFIR) Z
GROUP BY POSTORT, POSTNUMMER, ADRESS, NAMN, BETECKNING, ARENDENR

