DECLARE @TABLE3 AS DBO.HANDELSETABLETYPEFNR
INSERT
INTO @TABLE3 (DIARIENUMMER, HUVUDFASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR)
SELECT DIARIENUMMER, HUVUDFASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR
FROM DBO.sp_xKirToFnr(@TABLE2)

