DECLARE @HANDELSER AS HANDELSETABLETYPE;INSERT INTO @HANDELSER (DIARIENUMMER, HUVUDFASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR)SELECT DIARIENUMMER, [Ärendets huvudfastighet], ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, cast(HÄNDELSEDATUM AS DATETIME), KOMMENTAR
FROM tempExcel.dbo.HändelserFörbud12020
;
DECLARE @TABLE2 AS DBO.HANDELSETABLETYPE INSERT INTO @TABLE2 (DIARIENUMMER, HUVUDFASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR) SELECT Z.DIARIENUMMER, Z.HUVUDFASTIGHET, Z.ÄRENDEMENING, Z.TEXT, Z.RUBRIK, Z.RIKTNING, Z.DATUM, Z.ARENDEKOMMENTAR FROM
    [tempExcel].[dbo].sp_xCheckThatItsNotBadHadelseNa(@HANDELSER) Z
    INNER JOIN
	usp_xFilterByHasArende(@HANDELSER) Q ON Q.ID = Z.ID
    INNER JOIN
    	DBO.sp_xFilterSenasteMedKon(@HANDELSER) Y ON Z.ID = Y.ID
