
BEGIN TRAN
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Create Table ArtistUrl
CREATE TABLE [dbo].[ArtistUrl] (
		[Url]        [nvarchar](100) COLLATE Finnish_Swedish_CI_AS NULL,
		[Date]       [date] NOT NULL,
		[Artist]     [nvarchar](255) COLLATE Finnish_Swedish_CI_AS NOT NULL,
		CONSTRAINT [PK_ArtistUrl]
		PRIMARY KEY
		CLUSTERED
		([Artist])
	WITH (IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Add Default Constraint DF__Tracks-014__Date__44CA3770_ArtistUrl to ArtistUrl
ALTER TABLE [dbo].[ArtistUrl]
	ADD
	CONSTRAINT [DF__Tracks-014__Date__44CA3770_ArtistUrl]
	DEFAULT ('2013-01-23') FOR [Date]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Copying data from [dbo].[ Tracks-014034] to [dbo].[ArtistUrl]
INSERT INTO [dbo].[ArtistUrl](Url, [Date], Artist)
SELECT DISTINCT Url, [Date], Artist
FROM [dbo].[Tracks-014034_2013-01-23]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Drop Default Constraint DF__Tracks-014__Date__44CA3770 from  Tracks-014034
ALTER TABLE [dbo].[Tracks-014034_2013-01-23] DROP CONSTRAINT [DF__Tracks-014__Date__44CA3770]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Drop Column Url from  Tracks-014034
ALTER TABLE [dbo].[Tracks-014034_2013-01-23] DROP COLUMN [Url]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
-- Drop Column Date from  Tracks-014034
ALTER TABLE [dbo].[Tracks-014034_2013-01-23] DROP COLUMN [Date]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

IF @@TRANCOUNT>0
	COMMIT

SET NOEXEC OFF
GO

