USE [tempExcel]
GO
DROP PROCEDURE CP_FORBUD1UTSOK
/****** Object:  StoredProcedure [dbo].[Cp_Forbud1Utsok]    Script Date: 2020-04-28 16:19:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DBO.CP_FORBUD1UTSOK(@DIAX TT_ENDASTUNIKAARENDEN READONLY, @DIAKIR HANDELSETABLETYPE READONLY) AS
BEGIN
    DECLARE @FILTRARENDELATESTKONTAKT AS HANDELSETABLETYPE;
    DECLARE @HANDELSEKONTAKTER AS KONTAKTUPGTABLETYPE;
    DECLARE @ARENDEKONTAKTER AS KONTAKTUPGTABLETYPE;
    DECLARE @VISIONADRESSER AS KONTAKTUPGTABLETYPE;
    DECLARE @FIRPLVISION AS KONTAKTUPGTABLETYPE;
    DECLARE @FILTEREDBYMASTER AS HANDELSETABLETYPE;
    DECLARE @IDENT 
    TABLE  (FASTIGHET NVARCHAR(100), FNR          INT,DATUM        DATE DEFAULT getDate(), ANDEL        FLOAT DEFAULT 1.0,PERSORGNR NVARCHAR(100), NAMN NVARCHAR(100)
     )
    DECLARE @ADRESS TABLE  (PERSORGNR NVARCHAR(100),  CO NVARCHAR(100), UTADR1    NVARCHAR(100), UTADR2    NVARCHAR(100), POSTNR    NVARCHAR(100), POSTORT NVARCHAR(100))
    DECLARE @PLFA_LAGFART_V2 TABLE (FASTIGHET   NVARCHAR(100), FNR         INT, DATE         DATE DEFAULT getDate(), ANDEL        FLOAT DEFAULT 1.0, PERSORGNR   NVARCHAR(100), NAMN        NVARCHAR(100), FAL_CO NVARCHAR(100), FAL_UTADR1  NVARCHAR(100), FAL_UTADR2  NVARCHAR(100), FAL_POSTNR  NVARCHAR(100), FAL_POSTORT NVARCHAR(100), SAL_CO      NVARCHAR(100), SAL_UTADR1  NVARCHAR(100), SAL_UTADR2  NVARCHAR(100), SAL_POSTNR NVARCHAR(100), SAL_POSTORT NVARCHAR(100), UA_UTADR1   NVARCHAR(100), UA_UTADR2   NVARCHAR(100), UA_UTADR3 	NVARCHAR(100), UA_UTADR4   NVARCHAR(100), UA_LAND     NVARCHAR(100))

--(195 rows affected)
    IF OBJECT_ID('tempdb..#Results') IS NOT NULL 
    DROP TABLE #RESULTS 
    CREATE TABLE #RESULTS (
    DIANRX NVARCHAR(30)
    )
    INSERT #RESULTS 
    EXEC DBO.fn_xScalarDiaToTableDia @DIAX

--(433 rows affected)
    INSERT
    INTO @ARENDEKONTAKTER (DIARIENUMMER, FNR, HÄNDELSEDATUM, NAMN, POSTNUMMER, 
    POSTORT,GATUADRESS)
    SELECT X.DIANRX
	 , max(INTDIARIENUMMERLOEPNUMMER)
	 , max(RECENSTAKAKONTAKTID)
	 , STRVISASSOM
	 , STRPOSTNUMMER
	 , STRPOSTORT
	 , STRGATUADRESS
    FROM TEMPEXCEL.DBO.VISIONKONTAKTER VKVIEW
	JOIN #RESULTS 
	X ON VKVIEW.STRDIARIENUMMER = X.DIANRX
	WHERE VKVIEW.INTDIARIENUMMERLOEPNUMMER
	IS NULL
    GROUP BY X.DIANRX, STRVISASSOM, STRPOSTNUMMER, STRPOSTORT, 
    STRGATUADRESS
    PRINT concat(@@ROWCOUNT, ' rienummer')
    --(195 rows affected)
    INSERT
    INTO @HANDELSEKONTAKTER (DIARIENUMMER, FNR, HÄNDELSEDATUM, NAMN, POSTNUMMER, POSTORT, GATUADRESS)
    SELECT X.DIANRX
	 , max(INTDIARIENUMMERLOEPNUMMER)
	 , max(RECENSTAKAKONTAKTID)
	 , STRVISASSOM
	 , STRPOSTNUMMER
	 , STRPOSTORT
	 , STRGATUADRESS
    FROM TEMPEXCEL.DBO.VISIONKONTAKTER VKVIEW
    	Right OUTER 
	JOIN 
	#RESULTS X ON VKVIEW.STRDIARIENUMMER = X.DIANRX
    WHERE VKVIEW.INTDIARIENUMMERLOEPNUMMER 
    IS NOT NULL
    GROUP BY X.DIANRX, STRVISASSOM, STRPOSTNUMMER, STRPOSTORT, 
    STRGATUADRESS
    PRINT concat(@@ROWCOUNT, 'iarienummer')
--(0 rows affected)
    INSERT
    INTO @FILTRARENDELATESTKONTAKT (DIARIENUMMER, FASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR)
    SELECT
     XCHECKTHATITSNOTBADHADELSENA.DIARIENUMMER,
     XCHECKTHATITSNOTBADHADELSENA.FASTIGHET,
     XCHECKTHATITSNOTBADHADELSENA.ÄRENDEMENING,
     XCHECKTHATITSNOTBADHADELSENA.TEXT,
     XCHECKTHATITSNOTBADHADELSENA.RUBRIK,
     XCHECKTHATITSNOTBADHADELSENA.RIKTNING,
     XCHECKTHATITSNOTBADHADELSENA.DATUM,
      XCHECKTHATITSNOTBADHADELSENA.ARENDEKOMMENTAR
    FROM [tempExcel].[dbo].sp_xCheckThatItsNotBadHadelseNa(@DIAKIR) XCHECKTHATITSNOTBADHADELSENA
	INNER JOIN usp_xFilterByHasArende(@DIAKIR) Q ON Q.ID = XCHECKTHATITSNOTBADHADELSENA.ID
	INNER JOIN DBO.sp_xFilterSenasteMedKon(@DIAKIR) Y ON XCHECKTHATITSNOTBADHADELSENA.ID = Y.ID
    PRINT concat(@@ROWCOUNT, 'ntakt')
--(60 rows affected)
    INSERT
    INTO @FILTEREDBYMASTER (DIARIENUMMER, FASTIGHET, ÄRENDEMENING, TEXT, RUBRIK, RIKTNING, DATUM, ARENDEKOMMENTAR)
    SELECT DISTINCT V.DIANRX
		  , V.FASTIGHET
		  , Y.ARENDEKOMMENTAR
		  , Y.TEXT
		  , isnull(V.RUBRIK, '')
		  , Y.RIKTNING
		  , isnull(V.DATUM, GETDATE())
		  , Y.ARENDEKOMMENTAR
    FROM @FILTRARENDELATESTKONTAKT Y
	RIGHT OUTER JOIN(SELECT #RESULTS.DIANRX, Q.DATUM, Q.RUBRIK, Q.FASTIGHET
			 FROM #RESULTS
			     LEFT OUTER JOIN @DIAKIR Q ON 
			     #RESULTS.DIANRX = Q.DIARIENUMMER) V
	ON V.DIANRX = Y.DIARIENUMMER
    PRINT concat(@@ROWCOUNT, 'iarienummer')
--(433 rows affected)
    INSERT
    INTO @VISIONADRESSER 
    (DIARIENUMMER, FNR, 

    HÄNDELSEDATUM, 
    NAMN, 
    POSTNUMMER, 
    POSTORT, 
    GATUADRESS,
    FASTIGHET
    )
    SELECT KIR.DIARIENUMMER
	 , KIR.FNR
	 , 2020 - 10 - 10 HÄNDELSEDATUM
	 , NAMN
	 , DBO.udf_xGetNumeric(POSTNUMMER) POSTNUMMER
	 , POSTORT
	 , GATUADRESS
	  , VISION.FASTIGHET
    FROM (SELECT * 
FROM @HANDELSEKONTAKTER H UNION SELECT * 
FROM @ARENDEKONTAKTER A)
 VISION
    Right OUTER JOIN 
         (SELECT * FROM DBO.sp_xKirToFnr(@FILTEREDBYMASTER)) KIR
	 ON VISION.DIARIENUMMER = KIR.DIARIENUMMER
    PRINT concat(@@ROWCOUNT, ' rienummer')
    --vision handelser does include personnr, it does also include a country and company feild, and it would be silly not to use it before this step.
    -- does this step find missing personnr?
--(195 rows affected)
    INSERT
    INTO @FIRPLVISION (DIARIENUMMER, FNR, FASTIGHET, HÄNDELSEDATUM, NAMN, POSTNUMMER, GATUADRESS, POSTORT, PERSONNR)
    SELECT DIARIENUMMER, FNR, FASTIGHET, HÄNDELSEDATUM, NAMN, POSTNUMMER, GATUADRESS, POSTORT, PERSONNR
    FROM DBO.sp_xKonUpgToAdr(@VISIONADRESSER)
    PRINT concat(@@ROWCOUNT, 'nummer')
    -- why do we do this process manually, don't we do this similary above?
    -- maybe worth doing a moduel , that takes any source, returning digestable ressults
--(0 rows affected)
    INSERT
    INTO @PLFA_LAGFART_V2 (FAL_POSTNR, FAL_POSTORT, PERSORGNR, FASTIGHET, FNR, DATE, ANDEL,NAMN, FAL_CO, FAL_UTADR1, FAL_UTADR2, SAL_CO, SAL_UTADR1, SAL_UTADR2, SAL_POSTNR, SAL_POSTORT, UA_UTADR1, UA_UTADR2, UA_UTADR3, UA_UTADR4, UA_LAND)
    SELECT 
    DISTINCT 
    PERSORGNR, 
  FAL_POSTNR POSTNR, 
  FAL_POSTORT POSTORT
    ,RESS.FASTIGHET
		  , RESS.FNR
		  , INSKDATUM                                                          'date'
		  , cast(left(ANDEL, charindex('/', ANDEL, 1) - 1) AS FLOAT) /
		    cast(right(ANDEL, len(ANDEL) - charindex('/', ANDEL, 1)) AS FLOAT) ANDEL
 		  , FIR.NAMN
		  , FAL_CO
		  , FAL_UTADR1
		  , FAL_UTADR2
		  , SAL_CO
		  , SAL_UTADR1
		  , SAL_UTADR2
		  , SAL_POSTNR
		  , SAL_POSTORT
		  , UA_UTADR1
		  , UA_UTADR2
		  , UA_UTADR3
		  , UA_UTADR4
		  , UA_LAND
    FROM (SELECT *
	  FROM (SELECT DIARIENUMMER, FNR, FASTIGHET, CC_PRIO, 
	  avg(CC_PRIO) OVER (PARTITION BY FNR) / 500 KOMPLETT
		FROM @FIRPLVISION) A
	  WHERE KOMPLETT < 1) RESS
	JOIN GISDATA.SDE_GEOFIR_GOTLAND.GNG.FA_LAGFART_V2 FIR ON RESS.FNR = FIR.FNR
    PRINT concat(@@ROWCOUNT, ' stighet')
--(0 rows affected)
    INSERT INTO @IDENT SELECT FASTIGHET, FNR, DATE, ANDEL, PERSORGNR, NAMN 
    FROM @PLFA_LAGFART_V2
    PRINT concat(@@ROWCOUNT, ' et')
--(0 rows affected)
    INSERT
    INTO @ADRESS
    SELECT PERSORGNR, FAL_CO, FAL_UTADR1, FAL_UTADR2, FAL_POSTNR, FAL_POSTORT
    FROM @PLFA_LAGFART_V2
    UNION
    SELECT PERSORGNR, SAL_CO, SAL_UTADR1, SAL_UTADR2, SAL_POSTNR, SAL_POSTORT
    FROM @PLFA_LAGFART_V2
    UNION
    SELECT PERSORGNR, UA_UTADR1, UA_UTADR2, UA_UTADR3, UA_UTADR4, UA_LAND
    FROM @PLFA_LAGFART_V2
    PRINT concat(@@ROWCOUNT, 'GNR')
--(1 row affected)
    SELECT I.*, A.CO, A.UTADR1, A.UTADR2, A.POSTNR, A.POSTORT
    FROM (SELECT *
	  FROM @ADRESS
	  WHERE NOT (CO IS NULL AND UTADR1 IS NULL AND UTADR2 IS NULL AND POSTNR IS NULL AND POSTORT IS NULL)
	  GROUP BY PERSORGNR, CO, UTADR1, UTADR2, POSTNR, POSTORT) A
	JOIN @IDENT I ON I.PERSORGNR = A.PERSORGNR
END;
