FILTRERADEFAST AS (
SELECT SOCKEN SOCKENX, concat(TRAKT, ' ', BLOCKENHET) FASTIGHET, SHAPE
FROM SDE_GSD.GNG.AY_0980 X
    INNER JOIN
(SELECT VALUE "socken"
 FROM STRING_SPLIT(N'Källunge,Vallstena,Hörsne,Bara,Norrlanda,Stenkyrka', ',')) AS SOCKNAROFINTRESSE
    ON X.TRAKT LIKE SOCKNAROFINTRESSE.SOCKEN + '%')
,selection as (select OBJECTID, FLAGGSKIKTET_P_EVW.FASTIGHET as evwFASTIGHET, FASTIGHET_TILLSTAND, ARENDENUMMER, BESLUT_DATUM,FLAGGSKIKTET_P_EVW.STATUS, UTSKICK_DATUM, ANTECKNING, UTFORDDATUM, SLAMHAMTNING, ANTAL_BYGGNADER, ALLTIDSANT, FLAGGSKIKTET_P_EVW.SHAPE, GDB_GEOMATTR_DATA, SDE_STATE_ID, SKAPAD_DATUM, ANDRAD_DATUM, SOCKENX, FILTRERADEFAST.FASTIGHET
from sde_miljo_halsoskydd.gng.Flaggskiktet_p_evw
left OUTER JOIN FILTRERADEFAST on
FILTRERADEFAST.FASTIGHET = Flaggskiktet_p_evw.FASTIGHET
where coalesce( FILTRERADEFAST.FASTIGHET,Flaggskiktet_p_evw.FASTIGHET,Flaggskiktet_p_evw.FASTIGHET_TILLSTAND) is not null and SOCKENX is not null)
